{
	"OnFailure": "/trial_mdk_base/Actions/CreatePRFalure.action",
	"OnSuccess": "/trial_mdk_base/Actions/CloseModalPage_Complete.action",
	"Properties": {
		"PurReqnDescription": "#Page:CreatePR/#Control:Descr/#Value",
		"PurchaseRequisitionType": "#Page:CreatePR/#Control:PRType/#Value",
		"SourceDetermination": "#Page:CreatePR/#Control:SourceDet/#Value",
		"to_PurchaseReqnItem/CompanyCode": "#Page:CreatePR/#Control:CC/#Value",
		"to_PurchaseReqnItem/Material": "#Page:CreatePR/#Control:Mat/#Value",
		"to_PurchaseReqnItem/MaterialGroup": "#Page:CreatePR/#Control:MatGroup/#Value",
		"to_PurchaseReqnItem/Plant": "#Page:CreatePR/#Control:Plant/#Value",
		"to_PurchaseReqnItem/RequestedQuantity": "#Page:CreatePR/#Control:RequestedQuantity/#Value"
	},
	"ShowActivityIndicator": true,
	"Target": {
		"EntitySet": "A_PurchaseRequisitionHeader",
		"Service": "/trial_mdk_base/Services/trial300047.service"
	},
	"_Type": "Action.Type.ODataService.CreateEntity"
}